// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_ESSENTIA_IMPRESARIOSERIALIZATION_H_
#define FLATBUFFERS_GENERATED_ESSENTIA_IMPRESARIOSERIALIZATION_H_

#include "flatbuffers/flatbuffers.h"

namespace ImpresarioSerialization {

struct Essentia;
struct EssentiaBuilder;

struct Essentia FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef EssentiaBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MELTRANSFORMSIGNAL = 4,
    VT_RADIXES = 6
  };
  const flatbuffers::Vector<float> *melTransformSignal() const {
    return GetPointer<const flatbuffers::Vector<float> *>(VT_MELTRANSFORMSIGNAL);
  }
  const flatbuffers::Vector<float> *radixes() const {
    return GetPointer<const flatbuffers::Vector<float> *>(VT_RADIXES);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_MELTRANSFORMSIGNAL) &&
           verifier.VerifyVector(melTransformSignal()) &&
           VerifyOffset(verifier, VT_RADIXES) &&
           verifier.VerifyVector(radixes()) &&
           verifier.EndTable();
  }
};

struct EssentiaBuilder {
  typedef Essentia Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_melTransformSignal(flatbuffers::Offset<flatbuffers::Vector<float>> melTransformSignal) {
    fbb_.AddOffset(Essentia::VT_MELTRANSFORMSIGNAL, melTransformSignal);
  }
  void add_radixes(flatbuffers::Offset<flatbuffers::Vector<float>> radixes) {
    fbb_.AddOffset(Essentia::VT_RADIXES, radixes);
  }
  explicit EssentiaBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Essentia> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Essentia>(end);
    return o;
  }
};

inline flatbuffers::Offset<Essentia> CreateEssentia(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<float>> melTransformSignal = 0,
    flatbuffers::Offset<flatbuffers::Vector<float>> radixes = 0) {
  EssentiaBuilder builder_(_fbb);
  builder_.add_radixes(radixes);
  builder_.add_melTransformSignal(melTransformSignal);
  return builder_.Finish();
}

inline flatbuffers::Offset<Essentia> CreateEssentiaDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<float> *melTransformSignal = nullptr,
    const std::vector<float> *radixes = nullptr) {
  auto melTransformSignal__ = melTransformSignal ? _fbb.CreateVector<float>(*melTransformSignal) : 0;
  auto radixes__ = radixes ? _fbb.CreateVector<float>(*radixes) : 0;
  return ImpresarioSerialization::CreateEssentia(
      _fbb,
      melTransformSignal__,
      radixes__);
}

inline const ImpresarioSerialization::Essentia *GetEssentia(const void *buf) {
  return flatbuffers::GetRoot<ImpresarioSerialization::Essentia>(buf);
}

inline const ImpresarioSerialization::Essentia *GetSizePrefixedEssentia(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<ImpresarioSerialization::Essentia>(buf);
}

inline bool VerifyEssentiaBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<ImpresarioSerialization::Essentia>(nullptr);
}

inline bool VerifySizePrefixedEssentiaBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<ImpresarioSerialization::Essentia>(nullptr);
}

inline void FinishEssentiaBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<ImpresarioSerialization::Essentia> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedEssentiaBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<ImpresarioSerialization::Essentia> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace ImpresarioSerialization

#endif  // FLATBUFFERS_GENERATED_ESSENTIA_IMPRESARIOSERIALIZATION_H_
