// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_FLOATMORSEL_IMPRESARIOSERIALIZATION_H_
#define FLATBUFFERS_GENERATED_FLOATMORSEL_IMPRESARIOSERIALIZATION_H_

#include "flatbuffers/flatbuffers.h"

namespace ImpresarioSerialization {

struct Morsel;
struct MorselBuilder;

struct Morsel FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef MorselBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_FIELD = 4,
    VT_VALUE = 6
  };
  uint64_t field() const {
    return GetField<uint64_t>(VT_FIELD, 0);
  }
  float value() const {
    return GetField<float>(VT_VALUE, 0.0f);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_FIELD) &&
           VerifyField<float>(verifier, VT_VALUE) &&
           verifier.EndTable();
  }
};

struct MorselBuilder {
  typedef Morsel Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_field(uint64_t field) {
    fbb_.AddElement<uint64_t>(Morsel::VT_FIELD, field, 0);
  }
  void add_value(float value) {
    fbb_.AddElement<float>(Morsel::VT_VALUE, value, 0.0f);
  }
  explicit MorselBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Morsel> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Morsel>(end);
    return o;
  }
};

inline flatbuffers::Offset<Morsel> CreateMorsel(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t field = 0,
    float value = 0.0f) {
  MorselBuilder builder_(_fbb);
  builder_.add_field(field);
  builder_.add_value(value);
  return builder_.Finish();
}

inline const ImpresarioSerialization::Morsel *GetMorsel(const void *buf) {
  return flatbuffers::GetRoot<ImpresarioSerialization::Morsel>(buf);
}

inline const ImpresarioSerialization::Morsel *GetSizePrefixedMorsel(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<ImpresarioSerialization::Morsel>(buf);
}

inline bool VerifyMorselBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<ImpresarioSerialization::Morsel>(nullptr);
}

inline bool VerifySizePrefixedMorselBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<ImpresarioSerialization::Morsel>(nullptr);
}

inline void FinishMorselBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<ImpresarioSerialization::Morsel> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedMorselBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<ImpresarioSerialization::Morsel> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace ImpresarioSerialization

#endif  // FLATBUFFERS_GENERATED_FLOATMORSEL_IMPRESARIOSERIALIZATION_H_
