// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_LEDPACKET_IMPRESARIOSERIALIZATION_H_
#define FLATBUFFERS_GENERATED_LEDPACKET_IMPRESARIOSERIALIZATION_H_

#include "flatbuffers/flatbuffers.h"

#include "RGBColor_generated.h"

namespace ImpresarioSerialization {

struct LedPacket;
struct LedPacketBuilder;

struct LedPacket FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef LedPacketBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_LEDS = 4
  };
  const flatbuffers::Vector<const ImpresarioSerialization::RGBColor *> *leds() const {
    return GetPointer<const flatbuffers::Vector<const ImpresarioSerialization::RGBColor *> *>(VT_LEDS);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_LEDS) &&
           verifier.VerifyVector(leds()) &&
           verifier.EndTable();
  }
};

struct LedPacketBuilder {
  typedef LedPacket Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_leds(flatbuffers::Offset<flatbuffers::Vector<const ImpresarioSerialization::RGBColor *>> leds) {
    fbb_.AddOffset(LedPacket::VT_LEDS, leds);
  }
  explicit LedPacketBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  LedPacketBuilder &operator=(const LedPacketBuilder &);
  flatbuffers::Offset<LedPacket> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<LedPacket>(end);
    return o;
  }
};

inline flatbuffers::Offset<LedPacket> CreateLedPacket(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<const ImpresarioSerialization::RGBColor *>> leds = 0) {
  LedPacketBuilder builder_(_fbb);
  builder_.add_leds(leds);
  return builder_.Finish();
}

inline flatbuffers::Offset<LedPacket> CreateLedPacketDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<ImpresarioSerialization::RGBColor> *leds = nullptr) {
  auto leds__ = leds ? _fbb.CreateVectorOfStructs<ImpresarioSerialization::RGBColor>(*leds) : 0;
  return ImpresarioSerialization::CreateLedPacket(
      _fbb,
      leds__);
}

inline const ImpresarioSerialization::LedPacket *GetLedPacket(const void *buf) {
  return flatbuffers::GetRoot<ImpresarioSerialization::LedPacket>(buf);
}

inline const ImpresarioSerialization::LedPacket *GetSizePrefixedLedPacket(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<ImpresarioSerialization::LedPacket>(buf);
}

inline bool VerifyLedPacketBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<ImpresarioSerialization::LedPacket>(nullptr);
}

inline bool VerifySizePrefixedLedPacketBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<ImpresarioSerialization::LedPacket>(nullptr);
}

inline void FinishLedPacketBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<ImpresarioSerialization::LedPacket> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedLedPacketBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<ImpresarioSerialization::LedPacket> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace ImpresarioSerialization

#endif  // FLATBUFFERS_GENERATED_LEDPACKET_IMPRESARIOSERIALIZATION_H_
