// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_LUMINARY_IMPRESARIOSERIALIZATION_H_
#define FLATBUFFERS_GENERATED_LUMINARY_IMPRESARIOSERIALIZATION_H_

#include "flatbuffers/flatbuffers.h"

#include "Color_generated.h"

namespace ImpresarioSerialization {

struct Luminary;
struct LuminaryBuilder;

struct Luminary FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef LuminaryBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_BRIGHTNESS = 4,
    VT_GLIMPSE = 6
  };
  uint8_t brightness() const {
    return GetField<uint8_t>(VT_BRIGHTNESS, 0);
  }
  const flatbuffers::Vector<const ImpresarioSerialization::Color *> *glimpse() const {
    return GetPointer<const flatbuffers::Vector<const ImpresarioSerialization::Color *> *>(VT_GLIMPSE);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_BRIGHTNESS) &&
           VerifyOffset(verifier, VT_GLIMPSE) &&
           verifier.VerifyVector(glimpse()) &&
           verifier.EndTable();
  }
};

struct LuminaryBuilder {
  typedef Luminary Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_brightness(uint8_t brightness) {
    fbb_.AddElement<uint8_t>(Luminary::VT_BRIGHTNESS, brightness, 0);
  }
  void add_glimpse(flatbuffers::Offset<flatbuffers::Vector<const ImpresarioSerialization::Color *>> glimpse) {
    fbb_.AddOffset(Luminary::VT_GLIMPSE, glimpse);
  }
  explicit LuminaryBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Luminary> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Luminary>(end);
    return o;
  }
};

inline flatbuffers::Offset<Luminary> CreateLuminary(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint8_t brightness = 0,
    flatbuffers::Offset<flatbuffers::Vector<const ImpresarioSerialization::Color *>> glimpse = 0) {
  LuminaryBuilder builder_(_fbb);
  builder_.add_glimpse(glimpse);
  builder_.add_brightness(brightness);
  return builder_.Finish();
}

inline flatbuffers::Offset<Luminary> CreateLuminaryDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint8_t brightness = 0,
    const std::vector<ImpresarioSerialization::Color> *glimpse = nullptr) {
  auto glimpse__ = glimpse ? _fbb.CreateVectorOfStructs<ImpresarioSerialization::Color>(*glimpse) : 0;
  return ImpresarioSerialization::CreateLuminary(
      _fbb,
      brightness,
      glimpse__);
}

inline const ImpresarioSerialization::Luminary *GetLuminary(const void *buf) {
  return flatbuffers::GetRoot<ImpresarioSerialization::Luminary>(buf);
}

inline const ImpresarioSerialization::Luminary *GetSizePrefixedLuminary(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<ImpresarioSerialization::Luminary>(buf);
}

inline bool VerifyLuminaryBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<ImpresarioSerialization::Luminary>(nullptr);
}

inline bool VerifySizePrefixedLuminaryBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<ImpresarioSerialization::Luminary>(nullptr);
}

inline void FinishLuminaryBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<ImpresarioSerialization::Luminary> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedLuminaryBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<ImpresarioSerialization::Luminary> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace ImpresarioSerialization

#endif  // FLATBUFFERS_GENERATED_LUMINARY_IMPRESARIOSERIALIZATION_H_
