// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_PITCH_IMPRESARIOSERIALIZATION_H_
#define FLATBUFFERS_GENERATED_PITCH_IMPRESARIOSERIALIZATION_H_

#include "flatbuffers/flatbuffers.h"

#include "PitchMethod_generated.h"

namespace ImpresarioSerialization {

struct Pitch;
struct PitchBuilder;

struct Pitch FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef PitchBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TIMESTAMP = 4,
    VT_METHOD = 6,
    VT_PITCH = 8,
    VT_CONFIDENCE = 10,
    VT_SAMPLETIMESTAMP = 12
  };
  uint64_t timestamp() const {
    return GetField<uint64_t>(VT_TIMESTAMP, 0);
  }
  ImpresarioSerialization::PitchMethod method() const {
    return static_cast<ImpresarioSerialization::PitchMethod>(GetField<int8_t>(VT_METHOD, 0));
  }
  float pitch() const {
    return GetField<float>(VT_PITCH, 0.0f);
  }
  float confidence() const {
    return GetField<float>(VT_CONFIDENCE, 0.0f);
  }
  uint64_t sampleTimestamp() const {
    return GetField<uint64_t>(VT_SAMPLETIMESTAMP, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_TIMESTAMP) &&
           VerifyField<int8_t>(verifier, VT_METHOD) &&
           VerifyField<float>(verifier, VT_PITCH) &&
           VerifyField<float>(verifier, VT_CONFIDENCE) &&
           VerifyField<uint64_t>(verifier, VT_SAMPLETIMESTAMP) &&
           verifier.EndTable();
  }
};

struct PitchBuilder {
  typedef Pitch Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_timestamp(uint64_t timestamp) {
    fbb_.AddElement<uint64_t>(Pitch::VT_TIMESTAMP, timestamp, 0);
  }
  void add_method(ImpresarioSerialization::PitchMethod method) {
    fbb_.AddElement<int8_t>(Pitch::VT_METHOD, static_cast<int8_t>(method), 0);
  }
  void add_pitch(float pitch) {
    fbb_.AddElement<float>(Pitch::VT_PITCH, pitch, 0.0f);
  }
  void add_confidence(float confidence) {
    fbb_.AddElement<float>(Pitch::VT_CONFIDENCE, confidence, 0.0f);
  }
  void add_sampleTimestamp(uint64_t sampleTimestamp) {
    fbb_.AddElement<uint64_t>(Pitch::VT_SAMPLETIMESTAMP, sampleTimestamp, 0);
  }
  explicit PitchBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  PitchBuilder &operator=(const PitchBuilder &);
  flatbuffers::Offset<Pitch> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Pitch>(end);
    return o;
  }
};

inline flatbuffers::Offset<Pitch> CreatePitch(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t timestamp = 0,
    ImpresarioSerialization::PitchMethod method = ImpresarioSerialization::PitchMethod::schmitt,
    float pitch = 0.0f,
    float confidence = 0.0f,
    uint64_t sampleTimestamp = 0) {
  PitchBuilder builder_(_fbb);
  builder_.add_sampleTimestamp(sampleTimestamp);
  builder_.add_timestamp(timestamp);
  builder_.add_confidence(confidence);
  builder_.add_pitch(pitch);
  builder_.add_method(method);
  return builder_.Finish();
}

inline const ImpresarioSerialization::Pitch *GetPitch(const void *buf) {
  return flatbuffers::GetRoot<ImpresarioSerialization::Pitch>(buf);
}

inline const ImpresarioSerialization::Pitch *GetSizePrefixedPitch(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<ImpresarioSerialization::Pitch>(buf);
}

inline bool VerifyPitchBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<ImpresarioSerialization::Pitch>(nullptr);
}

inline bool VerifySizePrefixedPitchBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<ImpresarioSerialization::Pitch>(nullptr);
}

inline void FinishPitchBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<ImpresarioSerialization::Pitch> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedPitchBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<ImpresarioSerialization::Pitch> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace ImpresarioSerialization

#endif  // FLATBUFFERS_GENERATED_PITCH_IMPRESARIOSERIALIZATION_H_
