// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SIGNALARIUM_IMPRESARIOSERIALIZATION_H_
#define FLATBUFFERS_GENERATED_SIGNALARIUM_IMPRESARIOSERIALIZATION_H_

#include "flatbuffers/flatbuffers.h"

namespace ImpresarioSerialization {

struct Signalarium;
struct SignalariumBuilder;

struct Signalarium FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef SignalariumBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_STFT = 4,
    VT_RADIXES = 6
  };
  const flatbuffers::Vector<float> *stft() const {
    return GetPointer<const flatbuffers::Vector<float> *>(VT_STFT);
  }
  const flatbuffers::Vector<float> *radixes() const {
    return GetPointer<const flatbuffers::Vector<float> *>(VT_RADIXES);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_STFT) &&
           verifier.VerifyVector(stft()) &&
           VerifyOffset(verifier, VT_RADIXES) &&
           verifier.VerifyVector(radixes()) &&
           verifier.EndTable();
  }
};

struct SignalariumBuilder {
  typedef Signalarium Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_stft(flatbuffers::Offset<flatbuffers::Vector<float>> stft) {
    fbb_.AddOffset(Signalarium::VT_STFT, stft);
  }
  void add_radixes(flatbuffers::Offset<flatbuffers::Vector<float>> radixes) {
    fbb_.AddOffset(Signalarium::VT_RADIXES, radixes);
  }
  explicit SignalariumBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Signalarium> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Signalarium>(end);
    return o;
  }
};

inline flatbuffers::Offset<Signalarium> CreateSignalarium(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<float>> stft = 0,
    flatbuffers::Offset<flatbuffers::Vector<float>> radixes = 0) {
  SignalariumBuilder builder_(_fbb);
  builder_.add_radixes(radixes);
  builder_.add_stft(stft);
  return builder_.Finish();
}

inline flatbuffers::Offset<Signalarium> CreateSignalariumDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<float> *stft = nullptr,
    const std::vector<float> *radixes = nullptr) {
  auto stft__ = stft ? _fbb.CreateVector<float>(*stft) : 0;
  auto radixes__ = radixes ? _fbb.CreateVector<float>(*radixes) : 0;
  return ImpresarioSerialization::CreateSignalarium(
      _fbb,
      stft__,
      radixes__);
}

inline const ImpresarioSerialization::Signalarium *GetSignalarium(const void *buf) {
  return flatbuffers::GetRoot<ImpresarioSerialization::Signalarium>(buf);
}

inline const ImpresarioSerialization::Signalarium *GetSizePrefixedSignalarium(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<ImpresarioSerialization::Signalarium>(buf);
}

inline bool VerifySignalariumBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<ImpresarioSerialization::Signalarium>(nullptr);
}

inline bool VerifySizePrefixedSignalariumBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<ImpresarioSerialization::Signalarium>(nullptr);
}

inline void FinishSignalariumBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<ImpresarioSerialization::Signalarium> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedSignalariumBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<ImpresarioSerialization::Signalarium> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace ImpresarioSerialization

#endif  // FLATBUFFERS_GENERATED_SIGNALARIUM_IMPRESARIOSERIALIZATION_H_
