// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SPECTRALFLUX_IMPRESARIOSERIALIZATION_H_
#define FLATBUFFERS_GENERATED_SPECTRALFLUX_IMPRESARIOSERIALIZATION_H_

#include "flatbuffers/flatbuffers.h"

namespace ImpresarioSerialization {

struct SpectralFlux;
struct SpectralFluxBuilder;

struct SpectralFlux FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef SpectralFluxBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ORIGINTIMESTAMP = 4,
    VT_SPECTRALFLUXES = 6
  };
  uint64_t originTimestamp() const {
    return GetField<uint64_t>(VT_ORIGINTIMESTAMP, 0);
  }
  const flatbuffers::Vector<float> *spectralFluxes() const {
    return GetPointer<const flatbuffers::Vector<float> *>(VT_SPECTRALFLUXES);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_ORIGINTIMESTAMP) &&
           VerifyOffset(verifier, VT_SPECTRALFLUXES) &&
           verifier.VerifyVector(spectralFluxes()) &&
           verifier.EndTable();
  }
};

struct SpectralFluxBuilder {
  typedef SpectralFlux Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_originTimestamp(uint64_t originTimestamp) {
    fbb_.AddElement<uint64_t>(SpectralFlux::VT_ORIGINTIMESTAMP, originTimestamp, 0);
  }
  void add_spectralFluxes(flatbuffers::Offset<flatbuffers::Vector<float>> spectralFluxes) {
    fbb_.AddOffset(SpectralFlux::VT_SPECTRALFLUXES, spectralFluxes);
  }
  explicit SpectralFluxBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  SpectralFluxBuilder &operator=(const SpectralFluxBuilder &);
  flatbuffers::Offset<SpectralFlux> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<SpectralFlux>(end);
    return o;
  }
};

inline flatbuffers::Offset<SpectralFlux> CreateSpectralFlux(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t originTimestamp = 0,
    flatbuffers::Offset<flatbuffers::Vector<float>> spectralFluxes = 0) {
  SpectralFluxBuilder builder_(_fbb);
  builder_.add_originTimestamp(originTimestamp);
  builder_.add_spectralFluxes(spectralFluxes);
  return builder_.Finish();
}

inline flatbuffers::Offset<SpectralFlux> CreateSpectralFluxDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t originTimestamp = 0,
    const std::vector<float> *spectralFluxes = nullptr) {
  auto spectralFluxes__ = spectralFluxes ? _fbb.CreateVector<float>(*spectralFluxes) : 0;
  return ImpresarioSerialization::CreateSpectralFlux(
      _fbb,
      originTimestamp,
      spectralFluxes__);
}

inline const ImpresarioSerialization::SpectralFlux *GetSpectralFlux(const void *buf) {
  return flatbuffers::GetRoot<ImpresarioSerialization::SpectralFlux>(buf);
}

inline const ImpresarioSerialization::SpectralFlux *GetSizePrefixedSpectralFlux(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<ImpresarioSerialization::SpectralFlux>(buf);
}

inline bool VerifySpectralFluxBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<ImpresarioSerialization::SpectralFlux>(nullptr);
}

inline bool VerifySizePrefixedSpectralFluxBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<ImpresarioSerialization::SpectralFlux>(nullptr);
}

inline void FinishSpectralFluxBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<ImpresarioSerialization::SpectralFlux> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedSpectralFluxBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<ImpresarioSerialization::SpectralFlux> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace ImpresarioSerialization

#endif  // FLATBUFFERS_GENERATED_SPECTRALFLUX_IMPRESARIOSERIALIZATION_H_
