# automatically generated by the FlatBuffers compiler, do not modify

# namespace: ImpresarioSerialization

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class AudioAttributes(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsAudioAttributes(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = AudioAttributes()
        x.Init(buf, n + offset)
        return x

    # AudioAttributes
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # AudioAttributes
    def OnsetAggregate(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from ImpresarioSerialization.OnsetAggregate import OnsetAggregate
            obj = OnsetAggregate()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def AudioAttributesStart(builder): builder.StartObject(1)
def AudioAttributesAddOnsetAggregate(builder, onsetAggregate): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(onsetAggregate), 0)
def AudioAttributesEnd(builder): return builder.EndObject()
