# automatically generated by the FlatBuffers compiler, do not modify

# namespace: ImpresarioSerialization

import flatbuffers

class FloatMorsel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsFloatMorsel(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FloatMorsel()
        x.Init(buf, n + offset)
        return x

    # FloatMorsel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FloatMorsel
    def Field(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # FloatMorsel
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def FloatMorselStart(builder): builder.StartObject(2)
def FloatMorselAddField(builder, field): builder.PrependUint64Slot(0, field, 0)
def FloatMorselAddValue(builder, value): builder.PrependFloat32Slot(1, value, 0.0)
def FloatMorselEnd(builder): return builder.EndObject()
