# automatically generated by the FlatBuffers compiler, do not modify

# namespace: ImpresarioSerialization

class Identifier(object):
    axiomology = 0
    phenomenon = 1
    signalarium = 2
    luminary = 3

