# automatically generated by the FlatBuffers compiler, do not modify

# namespace: ImpresarioSerialization

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class LedPayload(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsLedPayload(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = LedPayload()
        x.Init(buf, n + offset)
        return x

    # LedPayload
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # LedPayload
    def Leds(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 3
            from ImpresarioSerialization.RGBColor import RGBColor
            obj = RGBColor()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # LedPayload
    def LedsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # LedPayload
    def LedsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def LedPayloadStart(builder): builder.StartObject(1)
def LedPayloadAddLeds(builder, leds): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(leds), 0)
def LedPayloadStartLedsVector(builder, numElems): return builder.StartVector(3, numElems, 1)
def LedPayloadEnd(builder): return builder.EndObject()
