# automatically generated by the FlatBuffers compiler, do not modify

# namespace: ImpresarioSerialization

import flatbuffers

class Luminary(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsLuminary(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Luminary()
        x.Init(buf, n + offset)
        return x

    # Luminary
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Luminary
    def Glimpse(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 3
            from .Color import Color
            obj = Color()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Luminary
    def GlimpseLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def LuminaryStart(builder): builder.StartObject(1)
def LuminaryAddGlimpse(builder, glimpse): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(glimpse), 0)
def LuminaryStartGlimpseVector(builder, numElems): return builder.StartVector(3, numElems, 1)
def LuminaryEnd(builder): return builder.EndObject()
