# automatically generated by the FlatBuffers compiler, do not modify

# namespace: ImpresarioSerialization

import flatbuffers

class Onset(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsOnset(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Onset()
        x.Init(buf, n + offset)
        return x

    # Onset
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Onset
    def Timestamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # Onset
    def Method(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

def OnsetStart(builder): builder.StartObject(2)
def OnsetAddTimestamp(builder, timestamp): builder.PrependUint64Slot(0, timestamp, 0)
def OnsetAddMethod(builder, method): builder.PrependInt8Slot(1, method, 0)
def OnsetEnd(builder): return builder.EndObject()
